config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root "pages#home"
  get "about", to: "pages#about"
  get "signup", to: "users#new"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  before_save { self.email = email.downcase }
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :username, presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                        uniqueness: { case_senitive: false },
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.first

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account infomation was successfully updated"
      redirect_to articles_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog, you have successfully sign up"
      redirect_to articles_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
</div>

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @article %> 
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded") do |f| %>
        <div class="row mb-3">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-center mb-3">
    <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info text-decoration-none" %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit article</h1>
<%= render "form" %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles listing</h1>

<div class="container">
  <% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          by <%= article.user.username if article.user %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success text-decoration-none" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
        </div>
        <div class="card-footer text-body-secondary">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Create a new article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          by <%= @article.user.username if @article.user %>
        </div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
        </div>
        <div class="card-footer text-body-secondary">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; Your Website</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
                <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <div id="page-content">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to "Articles listing", articles_path %> | 
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="p-5 mb-4 jumbotron text-center text-white rounded-3">
        <div class="py-5">
            <h1 class="display-4">Alpha Blog</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spcing to space content out within the larger container.</p>
            <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %>
        </div>
    </div>    
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<h4 class="alert-heading">The following errors prevented <%= obj.class.name.downcase %> from being saved</h4>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @user %> 
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded") do |f| %>
        <div class="row mb-3">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow", placeholder: "Enter a username" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow", placeholder: "Enter your email address" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow", placeholder: "Enter password" %>
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>

      <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-center mb-3">
    <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info text-decoration-none" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your profile</h1>

<%= render "form" %>

app/views/users/new.html.erb
<h1 class="text-center">Sign up for Alpha Blog</h1>

<%= render "form" %>